### PR TITLE
Project updates

### PR DESCRIPTION
**Pull request by friederbluemle**
Several project updates and cleanups:

- bintray-release `0.5.0`
- Gradle wrapper `4.0.1`

This also fixes all whitespace errors in a separate commit. Let me know if you prefer a separate PR for it. If the commits are reviewed individually, it shouldn't be a problem.

I also removed the forced daemon usage from `gradle.properties`. This should be a *machine-specific* setting. On CI for instance, the daemon should *not* be used.

<sub><sup>Please NO GitHub rebase/squash merges. The changes are broken up into meaningful, independent commits, and my branch should already be up-to-date with the latest target branch. If not, or if you'd like me to combine some or all of the commits, please let me know, and I will make the necessary updates as soon as possible. Thank you!</sup></sub>

### CODE REVIEW

**Comment by TroubleMakerBen** [comment]
Hey Frieder,

Thanks for the contribution! You're awesome!
We're working on making HA Android ready for Android O and your contribution will be part of that release.

Thx for using HockeyApp!
Benny

**Comment by friederbluemle** [comment]
Thanks Benny! Great to see the `HockeySDK-Android` repo is actively maintained. 👍 We're currently deciding on a beta test distribution tool at the company I work for, and HockeyApp is one of the contenders. It seems like Applivery has much less activity here on GitHub.

**Comment by TroubleMakerBen** [comment]
Yeah, we're committed to providing the best support we can and be a good citizen of the mobile developer community.

We're actually building the "next version" of HockeyApp, which is called [Mobile Center](https://www.hockeyapp.net/mobile-center/about/). It's in public preview right now, and HockeyApp will be around for a looong time. But Mobile Center is the future and it's the same friendly people ;)

Let me know if you have questions or feedback.

**Comment by friederbluemle** [comment]
Wow, Mobile Center looks awesome! Didn't know about it yet. Thanks for the link!

**Comment by TroubleMakerBen** [comment]
@friederbluemle you're welcome! Again, if you have questions, or run into any issues, please get in touch!

**Comment by TroubleMakerBen** [comment]
@friederbluemle They are!

[iOS](https://github.com/Microsoft/mobile-center-sdk-ios)
[Android](https://github.com/Microsoft/mobile-center-sdk-android)
[.Net/Xamarin](https://github.com/Microsoft/mobile-center-sdk-dotnet)
[React Native](https://github.com/Microsoft/mobile-center-sdk-react-native)

**Pull request merged**
