### PR TITLE
Changes to Authenticate via Email

### PR DESCRIPTION
**Pull request by rathimmi**
We are enabling authentication to hockey app via Email only by passing the email ID as a parameter instead of prompting a login screen

### CODE REVIEW

**Comment by TroubleMakerBen** [comment]
Thx for the contribution @rathimmi.
Please make sure this compiles and the CI passes

**Comment by TroubleMakerBen** [comment]
Hey @rathimmi,

thx. Let me know if you have other questions.

Best,
Benjamin

**Comment by rathimmi** [comment]
Is this request good enough to be approved ?

**Comment by TroubleMakerBen** [comment]
Hey @rathimmi,

sorry that it took me so long to respond to this.
Unfortunately we won't accept this PR as we don't want to bring this functionality to HockeyApp as we'd need to implement it across all platforms.
For now, you'd probably need to use your own fork.

Best,
Benjamin

**Pull request closed without merging**
