### PR TITLE
Feature/updated readme for 371

### PR DESCRIPTION
**Pull request by TroubleMakerBen**

### CODE REVIEW

**Comment by ranterle** [comment]
I believe the changelog should be placed in the release notes section of the repo - we could place a link to it. Otherwise we have bits of the changelog in the release notes section, some in the readme and a new file altogether.

**Comment by TroubleMakerBen** [comment]
About Changelog: the reason why I put it in a sep. file was
a) I'd like to be able to PR and discuss it
b) without a tag, we can't draft a release, so we're sending around changelogs in slack or mail and I'd like to get rid of that.
Let's talk about this over coffee ;)

About the capitalization of headlines:
I switched all headings to MLA-style and similar style guidelines.
Then I did some research and found that the [Microsoft Manual of Style](https://eucalyptus.atlassian.net/wiki/download/attachments/76611622/microsoft_manual_of_style_fourth_edition.pdf?version=2&modificationDate=1424379604164&api=v2) in it's latest edition says that only the first word in the headline should be start with a capital letter. 

I will unify this. =)

**Comment by TroubleMakerBen** [comment]
Oh, and while the command for LogCat itself is `logcat`, Google refers to the tool itself as *LogCat*, .e.g. [here](http://developer.android.com/tools/debugging/debugging-log.html#startingLogcat)

**Comment by ranterle** [comment]
Regarding LogCat: I stand corrected. :bow:

**Comment by ranterle** [comment]
Will merge this into the 3.7.1 release branch.

**Pull request closed without merging**
